//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace MuleSoft.DotNet.MaintenanceSystem
{ 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.mulesoft.samples.WorkOrderRequest_XML")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://com.mulesoft.samples.WorkOrderRequest_XML", IsNullable=false)]
public partial class WorkOrderRequests {
    
    private WorkOrderRequestsWorkOrderRequest[] workOrderRequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WorkOrderRequest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WorkOrderRequestsWorkOrderRequest[] WorkOrderRequest {
        get {
            return this.workOrderRequestField;
        }
        set {
            this.workOrderRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.mulesoft.samples.WorkOrderRequest_XML")]
public partial class WorkOrderRequestsWorkOrderRequest {
    
    private string machineNameField;
    
    private string machinedIDField;
    
    private string plantField;
    
    private string functionalLocationField;
    
    private string maintenanceTypeField;
    
    private System.DateTime requestDateField;
    
    private string workOrderIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MachineName {
        get {
            return this.machineNameField;
        }
        set {
            this.machineNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string MachinedID {
        get {
            return this.machinedIDField;
        }
        set {
            this.machinedIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Plant {
        get {
            return this.plantField;
        }
        set {
            this.plantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FunctionalLocation {
        get {
            return this.functionalLocationField;
        }
        set {
            this.functionalLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaintenanceType {
        get {
            return this.maintenanceTypeField;
        }
        set {
            this.maintenanceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime RequestDate {
        get {
            return this.requestDateField;
        }
        set {
            this.requestDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkOrderID {
        get {
            return this.workOrderIDField;
        }
        set {
            this.workOrderIDField = value;
        }
    }
}
}