//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

// 
namespace MuleSoft.DotNet.MaintenanceSystem
{ 
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.mulesoft.samples.WorkOrderCompletionRequest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://com.mulesoft.samples.WorkOrderCompletionRequest", IsNullable=false)]
public partial class WorkOrderCompletionRequests {
    
    private WorkOrderCompletionRequestsWorkOrderCompletionRequest workOrderCompletionRequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WorkOrderCompletionRequestsWorkOrderCompletionRequest WorkOrderCompletionRequest {
        get {
            return this.workOrderCompletionRequestField;
        }
        set {
            this.workOrderCompletionRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.mulesoft.samples.WorkOrderCompletionRequest")]
public partial class WorkOrderCompletionRequestsWorkOrderCompletionRequest {
    
    private string workOrderIdField;
    
    private int hoursField;
    
    private bool isSuccessfulField;
    
    private string commentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkOrderId {
        get {
            return this.workOrderIdField;
        }
        set {
            this.workOrderIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool IsSuccessful {
        get {
            return this.isSuccessfulField;
        }
        set {
            this.isSuccessfulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
}
}