//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuleSoft.DotNet.ERP.WorkOrder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="workOrderRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class workOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string functionalLocationField;
        
        private int machineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string machineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maintenanceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string plantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime requestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string workOrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string functionalLocation {
            get {
                return this.functionalLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.functionalLocationField, value) != true)) {
                    this.functionalLocationField = value;
                    this.RaisePropertyChanged("functionalLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int machineID {
            get {
                return this.machineIDField;
            }
            set {
                if ((this.machineIDField.Equals(value) != true)) {
                    this.machineIDField = value;
                    this.RaisePropertyChanged("machineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string machineName {
            get {
                return this.machineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.machineNameField, value) != true)) {
                    this.machineNameField = value;
                    this.RaisePropertyChanged("machineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string maintenanceType {
            get {
                return this.maintenanceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.maintenanceTypeField, value) != true)) {
                    this.maintenanceTypeField = value;
                    this.RaisePropertyChanged("maintenanceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string plant {
            get {
                return this.plantField;
            }
            set {
                if ((object.ReferenceEquals(this.plantField, value) != true)) {
                    this.plantField = value;
                    this.RaisePropertyChanged("plant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string workOrderID {
            get {
                return this.workOrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.workOrderIDField, value) != true)) {
                    this.workOrderIDField = value;
                    this.RaisePropertyChanged("workOrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="workOrderRequestAck", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class workOrderRequestAck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string workOrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string workOrderID {
            get {
                return this.workOrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.workOrderIDField, value) != true)) {
                    this.workOrderIDField = value;
                    this.RaisePropertyChanged("workOrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exception", Namespace="http://samples.mulesoft.com/")]
    [System.SerializableAttribute()]
    public partial class Exception : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://samples.mulesoft.com/", ConfigurationName="WorkOrder.IProcessWorkOrder")]
    public interface IProcessWorkOrder {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace http://samples.mulesoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MuleSoft.DotNet.ERP.WorkOrder.Exception), Action="", Name="Exception")]
        MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderResponse ProcessWorkOrder(MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderResponse> ProcessWorkOrderAsync(MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrder request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessWorkOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessWorkOrder", Namespace="http://samples.mulesoft.com/", Order=0)]
        public MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderBody Body;
        
        public ProcessWorkOrder() {
        }
        
        public ProcessWorkOrder(MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://samples.mulesoft.com/")]
    public partial class ProcessWorkOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MuleSoft.DotNet.ERP.WorkOrder.workOrderRequest arg0;
        
        public ProcessWorkOrderBody() {
        }
        
        public ProcessWorkOrderBody(MuleSoft.DotNet.ERP.WorkOrder.workOrderRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessWorkOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessWorkOrderResponse", Namespace="http://samples.mulesoft.com/", Order=0)]
        public MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderResponseBody Body;
        
        public ProcessWorkOrderResponse() {
        }
        
        public ProcessWorkOrderResponse(MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://samples.mulesoft.com/")]
    public partial class ProcessWorkOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MuleSoft.DotNet.ERP.WorkOrder.workOrderRequestAck @return;
        
        public ProcessWorkOrderResponseBody() {
        }
        
        public ProcessWorkOrderResponseBody(MuleSoft.DotNet.ERP.WorkOrder.workOrderRequestAck @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessWorkOrderChannel : MuleSoft.DotNet.ERP.WorkOrder.IProcessWorkOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessWorkOrderClient : System.ServiceModel.ClientBase<MuleSoft.DotNet.ERP.WorkOrder.IProcessWorkOrder>, MuleSoft.DotNet.ERP.WorkOrder.IProcessWorkOrder {
        
        public ProcessWorkOrderClient() {
        }
        
        public ProcessWorkOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessWorkOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessWorkOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessWorkOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderResponse MuleSoft.DotNet.ERP.WorkOrder.IProcessWorkOrder.ProcessWorkOrder(MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrder request) {
            return base.Channel.ProcessWorkOrder(request);
        }
        
        public MuleSoft.DotNet.ERP.WorkOrder.workOrderRequestAck ProcessWorkOrder(MuleSoft.DotNet.ERP.WorkOrder.workOrderRequest arg0) {
            MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrder inValue = new MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrder();
            inValue.Body = new MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderBody();
            inValue.Body.arg0 = arg0;
            MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderResponse retVal = ((MuleSoft.DotNet.ERP.WorkOrder.IProcessWorkOrder)(this)).ProcessWorkOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderResponse> MuleSoft.DotNet.ERP.WorkOrder.IProcessWorkOrder.ProcessWorkOrderAsync(MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrder request) {
            return base.Channel.ProcessWorkOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderResponse> ProcessWorkOrderAsync(MuleSoft.DotNet.ERP.WorkOrder.workOrderRequest arg0) {
            MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrder inValue = new MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrder();
            inValue.Body = new MuleSoft.DotNet.ERP.WorkOrder.ProcessWorkOrderBody();
            inValue.Body.arg0 = arg0;
            return ((MuleSoft.DotNet.ERP.WorkOrder.IProcessWorkOrder)(this)).ProcessWorkOrderAsync(inValue);
        }
    }
}
